services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    image: gophercraft:latest
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      HTTP_ADDR: ":3000"

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./deploy/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    depends_on:
      - api

  grafana:
    image: grafana/grafana:latest
    ports:
      - "4000:3000"   # 3000 ya lo usa la API; mapeamos a 3001 en el host
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - ./deploy/grafana/provisioning:/etc/grafana/provisioning:ro
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  grafana-data:
