services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: gophercraft:latest
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      HTTP_ADDR: ":3000"
